contact_links:
  - name: Feature Template
    about: 機能追加/修正を行うIssueに使用するテンプレート
    labels: feature
    url: https://github.com/iwaseshi/issue-template-sample/issues/new?template=feature_template.md&projects=iwaseshi/projects/1&labels=feature
  - name: Bug Template
    about: バグの報告に使用するテンプレート
    labels: bug
    url: https://github.com/iwaseshi/issue-template-sample/issues/new?template=bug_template.md&projects=iwaseshi/projects/1&labels=bug
